### ISSUE TITLE
Swift Docs

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-ios#4]
- [x] Determine how to generate swift docs from a dynamic framework

**Comment by aj-michael** [comment]
Appledoc doesn't support swift yet. See:

https://github.com/tomaz/appledoc/issues/460

**Comment by robinsdm** [comment]
Is there any documentation tool that supports Swift yet? In this [StackOverflow post](http://stackoverflow.com/questions/24047991/does-swift-have-documentation-comments-or-tools) it looks like there is some tool that supports Swift.

**Comment by robinsdm** [comment]
Maybe [Jazzy](https://github.com/realm/jazzy).

**Comment by aj-michael** [comment]
Ok, it looks like the best practice is just Swift-flavored markdown: http://nshipster.com/swift-documentation/

Jazzy will turn the markdown into HTML that resembles Apple's developer docs. Sounds good to me. I'll give it a shot in #7

**Comment by aj-michael** [comment]
Ok, I've added Jazzy docs in #7.
