### ISSUE TITLE
Pathfinder iOS SDK

### ISSUE THREAD

**Issue by danhanson** [CSSE497/pathfinder-ios#6]
Create an SDK that allows iOS developers to use our service
- [x] can create vehicles
- ~~can online vehicle~~
- ~~can offline vehicle~~
- [x] vehicle position is updated automatically
- [x] can create commodity
- [ ] can cancel commodity
- [x] Can listen for vehicle, commodity, and route updates

**Comment by aj-michael** [comment]
We've decided that the SDK will not expose the ability to update vehicle position. Instead the SDK will just run a background thread that sends a new position periodically.

**Comment by aj-michael** [comment]
In the first week of this sprint, I designed and documented this SDK. In the next week I will implement it. Time spent so far: 8 hours.

**Comment by aj-michael** [comment]
In the second week of this sprint, I have now spent 12 hours. The online/offline stuff is not yet supported by the backend, so I could not implement it here.
