### ISSUE TITLE
Where to host documentation?

### ISSUE THREAD

**Issue by aj-michael** [CSSE497/pathfinder-ios#8]
We need to host our SDK documentation somewhere. Currently it exists inside the `/doc` folder of this repo. Ideally we would have a documentation section of our website.

@grovecj @robinsdm @hansondg

**Comment by robinsdm** [comment]
I believe you can create a folder in the gh-pages branch if you want.

**Comment by aj-michael** [comment]
I've put it in gh-pages for now: http://csse497.github.io/pathfinder-ios/

I'd like it to be hosted with our actual web page though.

**Comment by aj-michael** [comment]
gh-pages is sufficient for now.
